#ifndef __XRADIO_WLAN_H__
#define __XRADIO_WLAN_H__

enum XR_WIFI_EVENT {
	XR_WIFI_CONNECTED,
	XR_WIFI_DISCONNECTED,
	XR_WIFI_SCAN_SUCCESS,
	XR_WIFI_SCAN_FAILED,
	XR_WIFI_4WAY_HANDSHAKE_FAILED,
	XR_WIFI_CONNECT_FAILED,
	XR_WIFI_CONNECTION_LOSS,
	XR_WIFI_NETWORK_UP,
	XR_WIFI_NETWORK_DOWN,
};


#endif
