/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY¡¯S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS¡¯SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY¡¯S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __SUNXI_GPIO_H__
#define __SUNXI_GPIO_H__


#define SUNXI_GIC_START          32

#ifdef __cplusplus
extern "C" {
#endif

#define PA_BASE	0
#define PB_BASE	32
#define PC_BASE	64
#define PD_BASE	96
#define PE_BASE	128
#define PF_BASE	160
#define PG_BASE	192
#define PH_BASE	224
#define PI_BASE	256
#define PJ_BASE	288
#define PK_BASE	320
#define PL_BASE	352
#define PM_BASE	384
#define PN_BASE	416
#define PO_BASE	448

/* sunxi gpio name space */
#define GPIOA(n)	(PA_BASE + (n))
#define GPIOB(n)	(PB_BASE + (n))
#define GPIOC(n)	(PC_BASE + (n))
#define GPIOD(n)	(PD_BASE + (n))
#define GPIOE(n)	(PE_BASE + (n))
#define GPIOF(n)	(PF_BASE + (n))
#define GPIOG(n)	(PG_BASE + (n))
#define GPIOH(n)	(PH_BASE + (n))
#define GPIOI(n)	(PI_BASE + (n))
#define GPIOJ(n)	(PJ_BASE + (n))
#define GPIOK(n)	(PK_BASE + (n))
#define GPIOL(n)	(PL_BASE + (n))
#define GPIOM(n)	(PM_BASE + (n))
#define GPION(n)	(PN_BASE + (n))
#define GPIOO(n)	(PO_BASE + (n))

/* use for check pin vailed and must include gpio-sun8iw18p1.h
 * after nane space macro
 *
 */

#include "../gpio-sun8iw18p1.h"
#define GPIO_MAX_BANK PH_BASE

#ifdef __cplusplus
}
#endif

#endif
